https://github.com/yu-steven/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz

name: Nodes

# 触发条件
on:
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  Collecting:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 执行任务
      # env:
      #   CONFIG: ${{ secrets.CONFIG }}
      run: |
        python ./utils/list_merge.py
    - name: 提交更改
      run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         git pull
         git status
         git add url
         git add long
         git add ./sub
         git add ./utils
         git commit -m "$(date '+%Y.%m.%d %H:%M:%S')更新订阅"
         git push origin devmain
    - name: 5分钟
      run: |
         sleep 5m
    - name: 安装Subconverter
      run: |
         wget https://github.com/yu-steven/subconverter/releases/download/v0.7.2/subconverter_linux64.tar.gz -O subconverter.tar.gz&&tar -zxvf subconverter.tar.gz&&nohup ./subconverter/subconverter &
    - name: 转译
      run: |
         wget "https://raw.githubusercontent.com/yu-steven/openit/main/long" -O https
         wget "http://0.0.0.0:25500/sub?target=clash&url=https://raw.githubusercontent.com/yu-steven/openit/main/long&config=https://raw.githubusercontent.com/yu-steven/openit/main/sub/rule.ini&emoji=true&udp=true&sort=true" -O Clash.yaml
    - name: 提交更改
      run: |
         git pull
         git add https
         git add Clash.yaml
         git commit -m "$(date '+%Y.%m.%d %H:%M:%S')更新订阅"
         git push origin devmain
